### ISSUE TITLE
"NameError:global name 'atexit' not defined" message with --include or --exclude bed files

### ISSUE THREAD

**Issue by benjasriga** [brentp/poverlap#8]
Dear brentp,
I installed the dependencies commandr (1.3.2) and your toolshed (v0.4.4) and have used the poverlap function successfully except for when I specify --exclude or --include. I get the error below. 

python poverlap.py poverlap --a shuffle.Spib.bed --b shuffle.Pu1.bed -g mm9.ChromInfo.txt --exclude mm9.bad.bed > test3.res
Traceback (most recent call last):
  File "poverlap.py", line 374, in <module>
    main()
  File "poverlap.py", line 370, in main
    res = Run()
  File "/home/benjamir/.local/lib/python2.7/site-packages/lib/python2.7/site-packages/commandr/commandr.py", line 308, in Run
    return self.RunFunction(cmd_fn, cmd_name)
  File "/home/benjamir/.local/lib/python2.7/site-packages/lib/python2.7/site-packages/commandr/commandr.py", line 421, in RunFunction
    result = info.callable(**options_dict)
  File "poverlap.py", line 318, in poverlap
    a = zclude(zclude(a, exclude, True), include, False)
  File "poverlap.py", line 231, in zclude
    tmp = mktemp()
  File "poverlap.py", line 28, in mktemp
    atexit.register(rm, f)
NameError: global name 'atexit' is not defined

**Comment by brentp** [comment]
hi @benjasriga thanks for reporting. I just pushed a fix for this. Let me know if any problems.

**Comment by benjasriga** [comment]
You may be my newest hero. Thanks. Will try the new code.

Ben

On May 3, 2015, at 2:09 PM, Brent Pedersen - Bioinformatics <notifications@github.com<mailto:notifications@github.com>>
 wrote:


hi @benjasriga<https://github.com/benjasriga> thanks for reporting. I just pushed a fix for this. Let me know if any problems.
